-- MySQL Script generated by MySQL Workbench
-- 06/10/20 22:59:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados` (
  `id_empleado` INT NULL AUTO_INCREMENT,
  `nombre_empleado` VARCHAR(45) NULL,
  `domicilio_empleado` VARCHAR(45) NULL,
  `tel_empleado` INT NOT NULL,
  `correo_empleado` VARCHAR(45) NULL,
  `AreaTrabajo` VARCHAR(45) NULL,
  `IdTaller(consulta Notaller)` INT NULL,
  `fecha_empleado` VARCHAR(45) NULL,
  `hora_empleado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehiculos` (
  `id_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `marca_vehiculo` VARCHAR(45) NULL,
  `modelo_vehiculo` VARCHAR(45) NULL,
  `matricula_vehiculo` VARCHAR(15) NULL,
  `año_vehiculo` INT(4) NOT NULL,
  `NoSerial_vehiculo` VARCHAR(17) NULL,
  `vehiculoscol` VARCHAR(45) NULL,
  `nobre_dueño(consulta nombre cliente)` VARCHAR(45) NULL,
  `hora_vehiculo` VARCHAR(45) NULL,
  `fecha_vehiculo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_vehiculo`, `año_vehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordenServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordenServicio` (
  `id_orden` INT NOT NULL AUTO_INCREMENT,
  `fecha_orden` VARCHAR(45) NULL,
  `descripcionFalla_orden` VARCHAR(1000) NULL,
  `observaciones_orden` TEXT(1000) NULL,
  `informeTecnico_orden` VARCHAR(45) NULL,
  `presupuesto_orden` FLOAT NULL,
  `Insumos_orden` VARCHAR(45) NULL,
  `estado_orden` VARCHAR(45) NULL,
  PRIMARY KEY (`id_orden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NULL,
  `domicilio_cliente` VARCHAR(45) NULL,
  `correo_cliente` VARCHAR(45) NOT NULL,
  `tel_cliente` INT NULL,
  `empresa_cliente` VARCHAR(45) NULL,
  `hora_cliente` VARCHAR(45) NULL,
  `fechacliente` VARCHAR(45) NULL,
  `vehiculos_id_vehiculo` INT NOT NULL,
  `vehiculos_año_vehiculo` INT(4) NOT NULL,
  PRIMARY KEY (`id_clientes`, `vehiculos_id_vehiculo`, `vehiculos_año_vehiculo`),
  INDEX `fk_clientes_vehiculos1_idx` (`vehiculos_id_vehiculo` ASC, `vehiculos_año_vehiculo` ASC),
  CONSTRAINT `fk_clientes_vehiculos1`
    FOREIGN KEY (`vehiculos_id_vehiculo` , `vehiculos_año_vehiculo`)
    REFERENCES `mydb`.`vehiculos` (`id_vehiculo` , `año_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin_taller` (
  `id_taller` INT NULL AUTO_INCREMENT,
  `nombre_taller` VARCHAR(20) NULL,
  `Intro_taller` TEXT(200) NULL,
  `Descripción_taller` TEXT(300) NULL,
  `image_taller` VARCHAR(200) NULL,
  `fecha_taller` VARCHAR(45) NULL,
  `hora_taller` VARCHAR(45) NULL,
  `empleados_id_empleado` INT NOT NULL,
  `vehiculos_id_vehiculo` INT NOT NULL,
  `vehiculos_año_vehiculo` INT(4) NOT NULL,
  `ordenServicio_id_orden` INT NOT NULL,
  `clientes_id_clientes` INT NOT NULL,
  PRIMARY KEY (`id_taller`, `clientes_id_clientes`),
  INDEX `fk_admin_taller_empleados_idx` (`empleados_id_empleado` ASC),
  INDEX `fk_admin_taller_vehiculos1_idx` (`vehiculos_id_vehiculo` ASC, `vehiculos_año_vehiculo` ASC),
  INDEX `fk_admin_taller_ordenServicio1_idx` (`ordenServicio_id_orden` ASC),
  INDEX `fk_admin_taller_clientes1_idx` (`clientes_id_clientes` ASC),
  CONSTRAINT `fk_admin_taller_empleados`
    FOREIGN KEY (`empleados_id_empleado`)
    REFERENCES `mydb`.`empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_taller_vehiculos1`
    FOREIGN KEY (`vehiculos_id_vehiculo` , `vehiculos_año_vehiculo`)
    REFERENCES `mydb`.`vehiculos` (`id_vehiculo` , `año_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_taller_ordenServicio1`
    FOREIGN KEY (`ordenServicio_id_orden`)
    REFERENCES `mydb`.`ordenServicio` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_taller_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `mydb`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordenServicio_has_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordenServicio_has_empleados` (
  `ordenServicio_id_orden` INT NOT NULL,
  `empleados_id_empleado` INT NOT NULL,
  PRIMARY KEY (`ordenServicio_id_orden`, `empleados_id_empleado`),
  INDEX `fk_ordenServicio_has_empleados_empleados1_idx` (`empleados_id_empleado` ASC),
  INDEX `fk_ordenServicio_has_empleados_ordenServicio1_idx` (`ordenServicio_id_orden` ASC),
  CONSTRAINT `fk_ordenServicio_has_empleados_ordenServicio1`
    FOREIGN KEY (`ordenServicio_id_orden`)
    REFERENCES `mydb`.`ordenServicio` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordenServicio_has_empleados_empleados1`
    FOREIGN KEY (`empleados_id_empleado`)
    REFERENCES `mydb`.`empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordenServicio_has_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordenServicio_has_clientes` (
  `ordenServicio_id_orden` INT NOT NULL,
  `clientes_id_clientes` INT NOT NULL,
  PRIMARY KEY (`ordenServicio_id_orden`, `clientes_id_clientes`),
  INDEX `fk_ordenServicio_has_clientes_clientes1_idx` (`clientes_id_clientes` ASC),
  INDEX `fk_ordenServicio_has_clientes_ordenServicio1_idx` (`ordenServicio_id_orden` ASC),
  CONSTRAINT `fk_ordenServicio_has_clientes_ordenServicio1`
    FOREIGN KEY (`ordenServicio_id_orden`)
    REFERENCES `mydb`.`ordenServicio` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordenServicio_has_clientes_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `mydb`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiculos_has_ordenServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehiculos_has_ordenServicio` (
  `vehiculos_id_vehiculo` INT NOT NULL,
  `vehiculos_año_vehiculo` INT(4) NOT NULL,
  `ordenServicio_id_orden` INT NOT NULL,
  PRIMARY KEY (`vehiculos_id_vehiculo`, `vehiculos_año_vehiculo`, `ordenServicio_id_orden`),
  INDEX `fk_vehiculos_has_ordenServicio_ordenServicio1_idx` (`ordenServicio_id_orden` ASC),
  INDEX `fk_vehiculos_has_ordenServicio_vehiculos1_idx` (`vehiculos_id_vehiculo` ASC, `vehiculos_año_vehiculo` ASC),
  CONSTRAINT `fk_vehiculos_has_ordenServicio_vehiculos1`
    FOREIGN KEY (`vehiculos_id_vehiculo` , `vehiculos_año_vehiculo`)
    REFERENCES `mydb`.`vehiculos` (`id_vehiculo` , `año_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculos_has_ordenServicio_ordenServicio1`
    FOREIGN KEY (`ordenServicio_id_orden`)
    REFERENCES `mydb`.`ordenServicio` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehiculos_has_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehiculos_has_empleados` (
  `vehiculos_id_vehiculo` INT NOT NULL,
  `vehiculos_año_vehiculo` INT(4) NOT NULL,
  `empleados_id_empleado` INT NOT NULL,
  PRIMARY KEY (`vehiculos_id_vehiculo`, `vehiculos_año_vehiculo`, `empleados_id_empleado`),
  INDEX `fk_vehiculos_has_empleados_empleados1_idx` (`empleados_id_empleado` ASC),
  INDEX `fk_vehiculos_has_empleados_vehiculos1_idx` (`vehiculos_id_vehiculo` ASC, `vehiculos_año_vehiculo` ASC),
  CONSTRAINT `fk_vehiculos_has_empleados_vehiculos1`
    FOREIGN KEY (`vehiculos_id_vehiculo` , `vehiculos_año_vehiculo`)
    REFERENCES `mydb`.`vehiculos` (`id_vehiculo` , `año_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculos_has_empleados_empleados1`
    FOREIGN KEY (`empleados_id_empleado`)
    REFERENCES `mydb`.`empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
